pool:
  vmImage: 'Ubuntu-16.04'

steps:

- task: AzureCLI@2
  displayName: Azure CLI
  inputs:
    azureSubscription: terraform
    scriptType: ps
    scriptLocation: inlineScript
    inlineScript: |
      az --version
      az account show

    

