pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: TerraformCLI@0
  inputs:
    command: 'init'
    allowTelemetryCollection: true
  displayName: Terraform Init
- task: TerraformCLI@0
  inputs:
    command: plan
    allowTelemetryCollection: true
  displayName: terraform plan

    

