pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: terraform@0
  inputs:
    command: 'init'
    providerAzureConnectedServiceName: 'terraform'
    backendAzureProviderStorageAccountName: 'mtcdenterraformsandbox'
  displayName: Terraform Init
    
- task: terraform@0
  inputs:
    command: 'plan'
    providerAzureConnectedServiceName: 'terraform'
    args: -var=environment=demo -out=tfplan.out
  displayName: Terraform Plan

- 
